### ISSUE TITLE
After upgrade to Linux Mint 19, stars are missing; Moon is giant pink square.

### ISSUE THREAD

**Issue by kauffy** [WulfMarius/Better-Night-Sky#1]
Due to a system problem, I upgraded my system from Mint 18.3 to Mint 19.

I am using nvidia-driver-390, which I believe I was using before the upgrade also.

My current save (the same one I sent you, for the Better-Placement bug), is in Aurora (the save you have may be just about to go) and the Aurora looks normal, but there are no stars visible at all, and the moon is a giant pink rectangle.

I've un-installed and re-installed the mod using Mod-Installer, but that had no effect.

Do you think the issue is with my config, or something in the mod? (Given that this issue hasn't been raised before, I think it might be my setup).

**Comment by WulfMarius** [comment]
Pink always points to some missing/corrupt shader.

If a reinstall isn't helping, then I would think a driver issue is the cause.

**Comment by WulfMarius** [comment]
I made a new release: https://github.com/WulfMarius/Better-Night-Sky/releases/tag/2.1.0  
It's also available via Mod-Installer.

Let me know if that fixes things.

**Comment by WulfMarius** [comment]
No further response from the reporter
